apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: agents
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- route.yaml
- agentruntime.yaml
- agentcard-configmap.yaml
- otel-tracing-configmap.yaml
